language: ruby
rvm:
  - 2.3.1

sudo: false

cache:
  directories:
    - vendor/bundle

install:
  - bundle install --deployment --jobs=3 --retry=3

before_script:
  - bundle exec rake db:create db:schema:load

script:
  - bundle exec rspec

# services:
  # - redis-server
addons:
  postgresql: 9.4
